version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/seed1.sql:/docker-entrypoint-initdb.d/seed1.sql
      - ./scripts/seed2.sql:/docker-entrypoint-initdb.d/seed2.sql
    env_file:
      - ./.env

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    depends_on:
      - db
    env_file:
      - ./.env
    command: sh -c "npm install && npm run dev"

volumes:
  postgres-data: