services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/01_init_db.sql:/docker-entrypoint-initdb.d/01_init_db.sql
      - ./scripts/02_create_tables.sql:/docker-entrypoint-initdb.d/02_create_tables.sql
      - ./scripts/03_insert_data.sql:/docker-entrypoint-initdb.d/03_insert_data.sql
      - ./scripts/04_revenue.sql:/docker-entrypoint-initdb.d/04_revenue.sql
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    command: sh -c "yarn install && yarn dev"

volumes:
  postgres-data:
