### Lấy toàn bộ assignment
GET http://localhost:3000/api/shift-employees
Content-Type: application/json


### Lấy assignment theo shiftID
GET http://localhost:3000/api/shift-employees/shift/SH_20250819_C3
Content-Type: application/json


### Lấy assignment theo employeeID
GET http://localhost:3000/api/shift-employees/employee/S001
Content-Type: application/json


### Tạo assignment mới
POST http://localhost:3000/api/shift-employees/create
Content-Type: application/json

{
  "date": "2025-09-29",
  "ca": "C3",
  "employeeId": "S001"
}


### Cập nhật assignment (thay đổi nhân viên trong shift)
PUT http://localhost:3000/api/shift-employees/SH_20250929_C3
Content-Type: application/json

{
  "shiftID" : "SH_20250929_C3",
  "newEmployeeId": "S003"
}


### Xóa assignment theo shiftID
DELETE http://localhost:3000/api/shift-employees/delete/SH_20250819_C3
Content-Type: application/json
